spring:
  datasource:
    url: jdbc:mysql://a2ss42.a2hosting.com:3306/bjoynesc_sfg_dev
    username: bjoynesc_dev_use
    password: recipe123
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
